create view [migration].vw_ParentAccounts as
(

select [Main Phone],
       Website,
       Owner,
       [Primary Contact],
       [Account Name],
       Fax,
       [Parent Account],
       [Ticker Symbol],
       Industry,
       [SIC Code],
       Ownership,
       Description,
       [Originating Lead],
       [Send Marketing Materials],
       [Preferred Method of Contact],
       [Do not allow Emails],
       [Do not allow Bulk Emails],
       [Do not allow Phone Calls],
       [Do not allow Faxes],
       [Do not allow Mails],
       Currency,
       [Credit Limit],
       [Credit Hold],
       [Payment Terms],
       [Address 1: Shipping Method],
       [Address 1: Freight Terms],
       [Follow Email Activity],
       [Account Number],
       Email,
       [Other Phone],
       [Address 1: Address Type],
       [Address 1: Name],
       [Address 1: Street 1],
       [Address 1: Street 2],
       [Address 1: Street 3],
       [Address 1: City],
       [Address 1: State/Province],
       [Address 1: ZIP/Postal Code],
       [Address 1: Country/Region],
       [Address Phone],
       [Annual Revenue],
       [Number of Employees],
       Territory,
       Category,
       [Relationship Type],
       [Price List],
       [Preferred Day],
       [Preferred User],
       [Preferred Time],
       [Existing Customer],
       [Industry Description]
from [migration].account
where [Parent Account] is not null)


create view [migration].vw_NonParentAccounts as
(

select [Main Phone],
       Website,
       Owner,
       [Primary Contact],
       [Account Name],
       Fax,
       [Parent Account],
       [Ticker Symbol],
       Industry,
       [SIC Code],
       Ownership,
       Description,
       [Originating Lead],
       [Send Marketing Materials],
       [Preferred Method of Contact],
       [Do not allow Emails],
       [Do not allow Bulk Emails],
       [Do not allow Phone Calls],
       [Do not allow Faxes],
       [Do not allow Mails],
       Currency,
       [Credit Limit],
       [Credit Hold],
       [Payment Terms],
       [Address 1: Shipping Method],
       [Address 1: Freight Terms],
       [Follow Email Activity],
       [Account Number],
       Email,
       [Other Phone],
       [Address 1: Address Type],
       [Address 1: Name],
       [Address 1: Street 1],
       [Address 1: Street 2],
       [Address 1: Street 3],
       [Address 1: City],
       [Address 1: State/Province],
       [Address 1: ZIP/Postal Code],
       [Address 1: Country/Region],
       [Address Phone],
       [Annual Revenue],
       [Number of Employees],
       Territory,
       Category,
       [Relationship Type],
       [Price List],
       [Preferred Day],
       [Preferred User],
       [Preferred Time],
       [Existing Customer],
       [Industry Description]
from [migration].account
where [Parent Account] is null)


create view [migration].vw_Template_Campaign as
(
select Name,
       [Campaign Code],
       Currency,
       [Campaign Type],
       [Expected Response Percentage],
       TmpRegardingObjectId,
       [Proposed Start Date],
       [Proposed End Date],
       [Actual Start Date],
       [Actual End Date],
       Offer,
       [Miscellaneous Costs],
       [Budget Allocated],
       Owner,
       Description,
       [Status Reason],
       [Price List],
       [Estimated Revenue]
from [migration].campaign)


create view [migration].vw_Template_Contact as
(
select [Company Name],
       Salutation,
       [First Name],
       [Middle Name],
       [Last Name],
       [Job Title],
       [Business Phone],
       [Home Phone],
       [Mobile Phone],
       Fax,
       Email,
       [Address 1: Address Type],
       [Address 1: Name],
       [Address 1: Street 1],
       [Address 1: Street 2],
       [Address 1: Street 3],
       [Address 1: City],
       [Address 1: State/Province],
       [Address 1: ZIP/Postal Code],
       [Address 1: Country/Region],
       [Address 1: Phone],
       [Address 1: Freight Terms],
       [Address 1: Shipping Method],
       Description,
       Department,
       Manager,
       [Manager Phone],
       Role,
       Assistant,
       [Assistant Phone],
       Gender,
       [Marital Status],
       [Spouse/Partner Name],
       Birthday,
       Anniversary,
       Owner,
       Currency,
       [Credit Limit],
       [Payment Terms],
       [Credit Hold],
       [Preferred Method of Contact],
       [Do not allow Emails],
       [Do not allow Phone Calls],
       [Do not allow Mails],
       [Do not allow Bulk Emails],
       [Do not allow Faxes],
       [Price List],
       [Originating Lead],
       [Send Marketing Materials],
       [Preferred Day],
       [Preferred Time],
       [Preferred Service],
       [Preferred Facility/Equipment],
       [Preferred User],
       [Follow Email Activity],
       [Email Address 2],
       [Business Phone 2],
       [Time Zone],
       [User Name],
       [Email Confirmed],
       [Mobile Phone Confirmed],
       [Two Factor Enabled],
       [Security Stamp],
       [Login Enabled],
       [Lockout Enabled],
       [Lockout End Date],
       [Access Failed Count],
       [Local Login Disabled],
       [Yomi Last Name],
       [Organization Name],
       Nickname,
       [Public Profile Copy],
       [Preferred Language],
       [Yomi First Name],
       Website,
       [Business Card],
       [Consent given],
       [GDPR is child],
       [Parent or custodian],
       [Do not track],
       [Source customer journey (Marketing)],
       [Source email (Marketing)],
       [Source form],
       [Marketing Only],
       [Source customer journey],
       [Source email],
       [Source landing page],
       [Source form (Marketing)],
       [Originating event],
       [Remember me]
from [migration].contact
    )
