with duplicate_quotes as (select [Quote ID], count(*) as [Count]
from [migration].quote
group by [Quote ID]
having count(*) > 1)

select *
from [migration].quote
where [Quote ID] in (select [Quote ID] from duplicate_quotes)
go


with duplicate_quotes as
    (
        select quotenumber, count(*) as [Count]
        from [staging].quote
        group by quotenumber
        having count(*) > 1
    )

select quoteid,
       odata_etag,
       _accountid_value,
       _campaignid_value,
       _contactid_value,
       _createdby_value,
       _createdby_value_lookuplogicalname,
       _createdby_value_FormattedValue,
       _createdonbehalfby_value,
       _customerid_value,
       _customerid_value_associatednavigationproperty,
       _customerid_value_lookuplogicalname,
       _customerid_value_FormattedValue,
       _mip_accountname_value,
       _mip_accountname_value_associatednavigationproperty,
       _mip_accountname_value_lookuplogicalname,
       _mip_accountname_value_FormattedValue,
       _mip_opportunity_value,
       _mip_opportunity_value_associatednavigationproperty,
       _mip_opportunity_value_lookuplogicalname,
       _mip_opportunity_value_FormattedValue,
       _modifiedby_value,
       _modifiedby_value_lookuplogicalname,
       _modifiedby_value_FormattedValue,
       _modifiedonbehalfby_value,
       _modifiedonbehalfby_value_lookuplogicalname,
       _modifiedonbehalfby_value_FormattedValue,
       _opportunityid_value,
       _opportunityid_value_associatednavigationproperty,
       _opportunityid_value_lookuplogicalname,
       _opportunityid_value_FormattedValue,
       _ownerid_value,
       _ownerid_value_associatednavigationproperty,
       _ownerid_value_lookuplogicalname,
       _ownerid_value_FormattedValue,
       _owningbusinessunit_value,
       _owningbusinessunit_value_associatednavigationproperty,
       _owningbusinessunit_value_lookuplogicalname,
       _owningbusinessunit_value_FormattedValue,
       _owningteam_value,
       _owninguser_value,
       _owninguser_value_lookuplogicalname,
       _pricelevelid_value,
       _pricelevelid_value_associatednavigationproperty,
       _pricelevelid_value_lookuplogicalname,
       _pricelevelid_value_FormattedValue,
       _slaid_value,
       _slainvokedid_value,
       _transactioncurrencyid_value,
       _transactioncurrencyid_value_associatednavigationproperty,
       _transactioncurrencyid_value_lookuplogicalname,
       _transactioncurrencyid_value_FormattedValue,
       billto_addressid,
       billto_city,
       billto_composite,
       billto_contactname,
       billto_country,
       billto_fax,
       billto_line1,
       billto_line2,
       billto_line3,
       billto_name,
       billto_postalcode,
       billto_stateorprovince,
       billto_telephone,
       closedon,
       createdon,
       createdon_FormattedValue,
       description,
       discountamount,
       discountamount_base,
       discountpercentage,
       discountpercentage_FormattedValue,
       effectivefrom,
       effectivefrom_FormattedValue,
       effectiveto,
       effectiveto_FormattedValue,
       emailaddress,
       exchangerate,
       exchangerate_FormattedValue,
       expireson,
       freightamount,
       freightamount_FormattedValue,
       freightamount_base,
       freightamount_base_FormattedValue,
       freighttermscode,
       importsequencenumber,
       lastonholdtime,
       mip_businessphone,
       mip_conversionrate,
       mip_conversionrate_FormattedValue,
       mip_conversionrate_aud,
       mip_conversionrate_aud_FormattedValue,
       mip_conversionrateusdtoaud,
       mip_discountedprice,
       mip_discountedprice_base,
       mip_discountedtraining,
       mip_fulladdress,
       mip_lastquotetotal,
       mip_lastquotetotal_base,
       mip_owneremail,
       mip_ownerphone,
       mip_quote_discount_percentage,
       mip_totalamount,
       mip_totalamount_FormattedValue,
       mip_totalamount_base,
       mip_totalamount_base_FormattedValue,
       mip_totaldetailamount,
       mip_totaldetailamount_FormattedValue,
       mip_totaldetailamount_base,
       mip_totaldetailamount_base_FormattedValue,
       mip_totaldiscountamount,
       mip_totaldiscountamount_FormattedValue,
       mip_totaldiscountamount_base,
       mip_totaldiscountamount_base_FormattedValue,
       mip_totalgst,
       mip_totalgst_FormattedValue,
       mip_totalgst_base,
       mip_totalgst_base_FormattedValue,
       mip_totalyear1end,
       mip_totalyear1start,
       mip_totalyear2end,
       mip_totalyear2start,
       mip_totalyear3end,
       mip_totalyear3start,
       mip_username,
       mip_year2price,
       mip_year2price_base,
       mip_year3price,
       mip_year3price_base,
       modifiedon,
       modifiedon_FormattedValue,
       name,
       onholdtime,
       overriddencreatedon,
       paymenttermscode,
       pricingerrorcode,
       pricingerrorcode_FormattedValue,
       processid,
       quotenumber,
       requestdeliveryby,
       revisionnumber,
       revisionnumber_FormattedValue,
       shippingmethodcode,
       shipto_addressid,
       shipto_city,
       shipto_composite,
       shipto_contactname,
       shipto_country,
       shipto_fax,
       shipto_freighttermscode,
       shipto_line1,
       shipto_line2,
       shipto_line3,
       shipto_name,
       shipto_postalcode,
       shipto_stateorprovince,
       shipto_telephone,
       skippricecalculation,
       stageid,
       statecode,
       statecode_FormattedValue,
       statuscode,
       statuscode_FormattedValue,
       versionnumber
from [staging].quote
where quotenumber in (select quotenumber from duplicate_quotes)
order by quotenumber
go

select *
from [migration].quoteclose
where Subject like '%QUO-01901-S3N0X8%'
